### PR TITLE
Correctly handle mosek status "near_optimal"

### PR DESCRIPTION
**Pull request by alexflint**
This changes the socp solver to deal with the mosek status "near_optimal"

### CODE REVIEW

**Comment by alexflint** [comment]
ping - can someone take a look at this?

**Comment by martinandersen** [comment]
Thanks for pointing out this issue. We will address this in the next release which unfortunately is long overdue. We will simply relay the MOSEK status to the user.

**Comment by martinandersen** [comment]
MOSEK's `near_optimal` status is now checked when returning the result. (See f2d5f03579a9b06eee924fd7467f3a9f53974bf5.)

**Comment by alexflint** [comment]
:+1:

**Pull request closed without merging**
